### ISSUE TITLE
No module named 'fused'

### ISSUE THREAD

**Issue by WoshiBoluo** [xrenaa/StyleSpace-pytorch#1]
![image](https://user-images.githubusercontent.com/52227723/114018906-59941b80-98a0-11eb-80e5-8d041abc97e1.png)
Hello, I have this problem with torch 1.7.1

**Comment by xrenaa** [comment]
I suggest you to use docker to run it : **thomasyt/gan-disc**. Hope this can help you.

**Comment by isack-ml** [comment]
I occur same issue so please explain in detail?
